print("")
print('print(type("This is a string"))')
print(type("This is a string"), end="\n\n")
print('print(type(2))')
print(type(2), end="\n\n")
print('print(type(2.6))')
print(type(2.6), end="\n\n")
print('print(type(1+2j))')
print(type(1+2j), end="\n\n")
print('print(type(True))')
print(type(True), end="\n\n")
print('print(type(None))')
print(type(None), end="\n")